### ISSUE TITLE
Investigate performance regression in Reachability with LinearMap

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1054]
In #472 we added a type parameter for the matrix of `LinearMap`. This significantly reduced the performance of an application in the `Reachability` package (see https://github.com/JuliaReach/Reachability.jl/issues/423). That is why we removed the type parameter again in #1037.
In this issue, we want to find out if we can get the type parameter back without a regression.

**Comment by mforets** [comment]
The "buffer" vector for each row-block is a vector of lazy linear maps. These should be concretely typed for best performance. Overall, i got 10x speedup with that (rather trivial) change, see [this notebook](https://github.com/mforets/escritoire/blob/master/reachability/BFFPSV18/BFFPSV18_homog.ipynb). Below in that notebooks there are other experiments if we assume that the row-blocks are of dimension one, since then we can reason about one-dimensional reachability with intervals (related to https://github.com/JuliaReach/Reachability.jl/issues/671).

**Comment by mforets** [comment]
In general, when we add a new type parameter for a lazy set, applications that use vectors of that type suddenly become type-unstable. This can bring regressions.

**Comment by schillic** [comment]
> In general, when we add a new type parameter for a lazy set, applications that use vectors of that type suddenly become type-unstable. This can bring regressions.

This is true, but I think this cannot be the reason here because the current implementation is this:
```julia
arr = Vector{LazySet{NUM}}(undef, arr_length)
```
So the type did not match `LinearMap{...}` at all even before adding the type parameter.
