### ISSUE TITLE
Use promotion for lazy operations on sets

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1182]
```julia
julia> using LazySets
[ Info: Recompiling stale cache file /Users/forets/.julia/compiled/v1.1/LazySets/NjrGc.ji for LazySets [b4f0291d-fe17-52bc-9479-3d1a343d9043]

julia> B = rand(Hyperrectangle)
Hyperrectangle{Float64}([-0.666225, -2.45121], [0.152791, 1.45867])

julia> M = [2 1; 0 1];

julia> M * B
ERROR: MethodError: no method matching *(::Array{Int64,2}, ::Hyperrectangle{Float64})
```

**Comment by schillic** [comment]
Is this restricted to lazy operations?

**Comment by mforets** [comment]
To keep this issue manageable i used "lazy operations". But we can apply promotion for concrete operations too such as `linear_map` in https://github.com/JuliaReach/LazySets.jl/pull/1156.

**Comment by mforets** [comment]
In v1.21.0,

```julia
julia> B = rand(Hyperrectangle)
Hyperrectangle{Float64,Array{Float64,1},Array{Float64,1}}([0.7726026879947012, 0.45486747218875573], [0.4694174319690279, 1.2415418135621428])

julia> M = [2 1; 0 1];

julia> M * B
LinearMap{Float64,Hyperrectangle{Float64,Array{Float64,1},Array{Float64,1}},Int64,Array{Int64,2}}([2 1; 0 1], Hyperrectangle{Float64,Array{Float64,1},Array{Float64,1}}([0.7726026879947012, 0.45486747218875573], [0.4694174319690279, 1.2415418135621428]))
```

**Comment by schillic** [comment]
The problem is that we mostly require the same numeric type for all arguments of a function. The original intention of that restriction was to detect type "losses" (e.g., when we use an LP solver with `Float32`, we get `Float64` out, which may deteriorate performance in subsequent computations). Having these promotion rules eliminates those checks, so we might as well just remove the restrictions. Since Julia promotes automatically, this should have the same performance. Having all these boilerplate conversion methods seems annoying and error-prone.

**Comment by mforets** [comment]
i don't see any actionable issue. should we close this one?
