### ISSUE TITLE
Fast disjointness test for zonotope and half-space

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1286]
A zonotope and a half-space are disjoint iff
1. any point in the zonotope (e.g., its center) is not in the half-space and 
2. the zonotope and the hyperplane corresponding to the half-space are disjoint.

(We have all the building blocks already.)

**Comment by mforets** [comment]
At the moment, disjointness check in this setting is computed with a single evaluation of the support function of the zonotope: https://github.com/JuliaReach/LazySets.jl/blob/master/src/is_intersection_empty.jl#L663  . It sounds like fast already. The point 1. is a nice test to have though.

**Comment by mforets** [comment]
> The point 1. is a nice test to have though.

i take back this point.  since the method in the OP requires at least two support function evaluations (for point 2, see figure), i don't think that it improves over what we have?

![Screenshot from 2020-09-01 15-32-10](https://user-images.githubusercontent.com/12424594/91892030-5846a480-ec68-11ea-85ae-e998771f7d63.png)

otoh, because of recents improvements in the zonotope-hyerplane disjointness code, it is now faster, but the two functions below shall be roughly the same:
 
```julia
julia> using Revise, LazySets, BenchmarkTools
[ Info: Precompiling LazySets [b4f0291d-fe17-52bc-9479-3d1a343d9043]

julia> Z = rand(Zonotope, dim=10); d = rand(10); H = rand(HalfSpace, dim=10);

julia> 

julia> X = Hyperplane(H.a, H.b);

julia> @btime isdisjoint($H, $Z) # half-space
  153.861 ns (2 allocations: 320 bytes) 
false

julia> @btime isdisjoint($X, $Z) # hyperplane
  70.273 ns (0 allocations: 0 bytes)
false

```

**Comment by schillic** [comment]
I agree that the proposal in the OP sounds more expensive. Indeed, with the latest version, the `HalfSpace` code is faster. The only thing to note is that it allocates more.

```julia
# support function (current implementation)
julia> @time isdisjoint(H, Z)
  0.000012 seconds (1 allocation: 144 bytes)
false

# proposed in OP
julia> @time Z.center ∉ X && isdisjoint(X, Z)
  0.000018 seconds (1 allocation: 32 bytes)
false

# step 1
julia> @time Z.center ∉ X
  0.000016 seconds (1 allocation: 32 bytes)
true

# step 1
julia> @time isdisjoint(X, Z)
  0.000009 seconds
false
```
