### ISSUE TITLE
Custom template directions

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1292]
Add a type `CustomDirections <: AbstractDirections` which just wraps a list of user-defined directions.

Note that there is no guarantee that an overapproximation resulting from those directions is bounded, so we have to check that (best in the constructor of that new type). How do we check that?

**Comment by mforets** [comment]
`AbstractDirections` are always unbounded, since they define rays of the form `λd` for each direction `d` and `λ` is a scalar.

I think that we can make the simplifying assumption that the set to be overapproximated is bounded, or put another way we don't yet have applications where the set `X` to be overapproximated is unbounded i believe, since we work with flowpipes. If usage arises we can change the assumption. Since we have `isbounded(::LazySet)` and is "fast" (since it reasons only about the type), it doesn't hurt to add the boundedness check (using dispatch) in the overapproximate functions, but again i think we don't need to make those changes until some interesting usage arises.

**Comment by schillic** [comment]
> AbstractDirections are always unbounded

I never asked whether the directions are unbounded.

>> there is no guarantee that an overapproximation resulting from those directions is bounded

I give an example. Take an interval `X = [0, 1]` and the singleton set of directions `D = {[1]}` (i.e., pointing to the positive end of the axis). The set `overapproximate(X, D)` will be a polyhedron `{x <= 1}` with a single half-space and thus unbounded.

> Since we have isbounded(::LazySet) and is "fast" (since it reasons only about the type)

This is true with one exception: `HPolyhedron`. Since we don't know automatically whether the set resulting from an overapproximation of an arbitrary set of directions is bounded or not (see the counterexample above), we would have to change the result to `HPolyhedron` in *all* cases. And thus we need to use an expensive check every time.

**Comment by mforets** [comment]
> I never asked whether the directions are unbounded.

#1292 adds `isbounded(::AbstractDirections)`, asking if the directions are unbounded.

> Take an interval X = [0, 1] and the singleton set of directions D = {[1]}

Got it, my point was that i've been assuming that `overapproximate(X, D)` is used with bounded `X` and such that if you let `di * x <= 1` for each `di` in `D` you get a bounded set. Overapproximating a bounded set with an unbounded set gives an infinite error in Hausdorff distance!

**Comment by schillic** [comment]
> #1292 adds isbounded(::AbstractDirections), asking if the directions are unbounded.

No, it asks whether the resulting set will be unbounded.
