### ISSUE TITLE
Left margin of some figures is cut

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#144]
Some left margins are cut in figures of `@example` blocks, such as the last of iterative refinement example.

**Comment by schillic** [comment]
I also do not have this problem locally.

The other two plots on above mentioned figure are also pressed to the left such that they partially overlap with the next plot. So I think instead of font size decrease you should rather add some space to the left. A hack might be to add a "y" axis label (empty/invisible if possible).

The problem *might* be with `GR` and that the Travis computers do not have a display. See the following warning from the build output:
```
[...]
Documenter: expanding markdown templates.
GKS: can't open display on ""
     Is your DISPLAY environment variable set correctly?
     Did you enable X11 and TCP forwarding?
[...]
```
But this warning could also be completely unrelated. In particular, this does not explain why we still get an almost-correct plot output...

**Comment by schillic** [comment]
Hot trace: Issue 1182 [here](https://github.com/JuliaPlots/Plots.jl).

**Comment by schillic** [comment]
The following pages were affected:
* [x] iterative refinement
* [ ] interval hulls
* [x] convex hulls
* [x] a reachability algorithm

#154 solved three of them. For the last one we might just reduce the image size a bit.
