### ISSUE TITLE
Minkowski sum of polyhedra

### ISSUE THREAD

**Issue by ueliwechsler** [JuliaReach/LazySets.jl#1476]
Sorry, for posting this question here, but on discourse, I got no answer and I am not sure, if I can use LazySets the way I'd like to. 
I would like to compute the Minkowsky sum of two HPolyhedron and then extract the resulting constraints to feed them into my JuMP model. 
For the 2D case, I can approximate the exact Polyhedron with overapproximate, like this:
```
n = 2
A = [Matrix{Float64}(I, n,n); -Matrix{Float64}(I, n,n)]
b = 0.1*ones(size(A,1))
hPoly = HPolyhedron(A, b)
minkowSum = hPoly ⊕ hPoly 
LazySets.Approximations.overapproximate(minkowSum , 1e-3)
```
However, for higher dimensional Polyhedron (e.g. n=3) overapproximate throws an error. Is there a way to approximate the HPolyhedron resulting from the Minkowsky addition for n=3 with LazySets or [Polyhedra](https://github.com/JuliaPolyhedra/Polyhedra.jl)?

**Comment by schillic** [comment]
We do not support epsilon-close approximation at the moment (see #969; contributions are welcome :wink:).
I wanted to suggest to compute the Minkowski sum via `minkowski_sum(hPoly1, hPoly2)`, but we also do not support that :astonished:
So I interpret this issue as the request to implement this method.
* [Here](https://pdfs.semanticscholar.org/7492/2769a31a4d6695f3ada51b05134f77b4fe5b.pdf) is a simple algorithm for constraint representation (your case).
* [Here](https://hal.archives-ouvertes.fr/hal-01092060/document) are two other algorithms for mixed representation.

**Comment by schillic** [comment]
@ueliwechsler: In this library we use the term "polytope" for a bounded "polyhedron" (the terminology differs). In your example, `hPoly` is bounded and you could use the type `HPolytope` instead. Is this a simplified example or are your sets *always* bounded?
I am asking because for the H-representation the algorithms I found are nontrivial to implement and in the bounded case you can convert to V-representation¹ and use #1477, which we could quickly implement.

¹ The conversion is not efficient in high dimensions, but at least it works.

**Comment by mforets** [comment]
> Sorry, for posting this question here,

Questions are welcome; we hadn't seen your [discourse question](https://discourse.julialang.org/t/lazysets-overapproximate-sum-of-two-hpolyhedron-in-3d-or-n-d/24396) 😄 

> So I interpret this issue as the request to implement this method. 

Interesting references @schillic, thanks for the links. Definitely worth having a close look.

`minkowski_sum(::VPolytope, ::VPolytope)`, at least the naive implementation, is easy to add. I'll take care of https://github.com/JuliaReach/LazySets.jl/issues/1477.

---

Let me note that if one is not interested in controlling the approximation error in Hausdorff distance (what we call epsilon-close approximation), which i presume it is the case, the calculation of above can be handled in higher dims using the *lazy* Minkowski sum and using template directions. Considering your example,

```julia
n = 3
A = [Matrix{Float64}(I, n,n); -Matrix{Float64}(I, n,n)]
b = 0.1*ones(size(A,1))
hPoly = HPolytope(A, b)
minkowSum = hPoly ⊕ hPoly 
dirs = SphericalDirections(10, 10)
oa = overapproximate(minkowSum, dirs)
```

<img width="633" alt="Screen Shot 2019-06-25 at 14 15 08" src="https://user-images.githubusercontent.com/12424594/60118925-b10cda00-9753-11e9-929f-660ad04490e2.png">


The code to generate the plot can be found in [this notebook](https://nbviewer.jupyter.org/github/mforets/escritoire/blob/master/sets/HigherDimRefinement.ipynb) (cf. https://github.com/JuliaReach/LazySets.jl/pull/1260/).

**Comment by schillic** [comment]
Note that `SphericalDirections` are only available in 3D, so you hit the same problem for `n >= 4` again unless you have a way of defining the template directions (normal directions of the resulting facets).

**Comment by mforets** [comment]
True. In higher dims we've got [box, or octagonal directions (or a combination of these)](https://juliareach.github.io/LazySets.jl/latest/lib/approximations/#Template-directions-1).

**Comment by ueliwechsler** [comment]
Thanks a lot, for the fast replies and solutions. I will try to implement, the `SphericalDirections` solution. However, it would be nice to have a solution for n-dimensional `HPolytopes`.
>Questions are welcome; we hadn't seen your discourse question 😄

Cool, thanks.

> @ueliwechsler: Is this a simplified example or are your sets _always_ bounded?

Yes, my set is always bounded, so it is always an `HPolytope`. Sorry, for the imprecision in my post. I am not that used to the terminology.
> which we could quickly implement

That would be great. In my use case, I would need to calculate efficiently the Minkowski sum and linear scaling of low dimensional Polytopes (n<=8, but at least for n=3). Along the line of 
```
using LazySets
using Polyhedra
P = rand(HPolytope, dim=n)
A = rand(n,n)
Pnew = A*P + P
LazySets.Approximations.overapproximate(Pnew, 1e-5)
```
I would also need to calculate the Pontryagin Difference of Polytopes but I think I have fixed this use for my use case and will open another issue to discuss this.

I could also implement things myself, but my knowledge of LazySets and set computation, in general, is rather limited. I would need some pointers on where to start in the code, and what exactly to implement.

**Comment by schillic** [comment]
> linear scaling

This is already available via the concrete operation `linear_map(A, P)`. As long as `A` is invertible, this operation is (relatively) efficient (because it does not have to convert to the V-representation).

> I would also need to calculate the Pontryagin Difference of Polytopes but I think I have fixed this use for my use case and will open another issue to discuss this.

Is this the same as the Minkowski difference? We had some discussion on that in #586, but never came back to it.

> I could also implement things myself, but my knowledge of LazySets and set computation, in general, is rather limited. I would need some pointers on where to start in the code, and what exactly to implement.

Great, we are happy to help you. Just open a new issue for the discussions or join the [Gitter channel](https://gitter.im/JuliaReach/Lobby).

**Comment by ueliwechsler** [comment]
> Is this the same as the Minkowski difference? We had some discussion on that in #586, but never came back to it. 

Yes, I think so. I opened a new issue #1478.

> minkowski_sum(::VPolytope, ::VPolytope), at least the naive implementation, is easy to add. I'll take care of #1477.

Concerning this implementation, can I be of any help in this?

**Comment by mforets** [comment]
> Concerning this implementation, can I be of any help in this?

Thanks but no problem, i have self-assigned this one, it is now PR #1479.

**Comment by schillic** [comment]
FYI, #1479 got merged to `master` and we will release a new version soon (#1487).

**Comment by mforets** [comment]
LazySets v1.14.0 is now released. An experiment with @ueliwechsler's example:

```julia
using LazySets, Polyhedra, Random

function f1476(n, backend=Polyhedra.default_library(n, Float64))
    rng = MersenneTwister(n) # for reproducibility
    
    P = convert(HPolytope, rand(Hyperrectangle, dim=n))
    # P = rand(HPolytope, dim=n, rng=rng) # don't do this; rand of HPolytope doesn't scale

    A = rand(rng, n, n)
    AP = linear_map(A, P) # this should be fast so long as A is invertible; otherwise it will use the Vrep but it is anyways needed below
    minkowski_sum(AP, P, backend=backend) # conversion to VPolytope and concrete minkowski sum is computed
end

# using Polyhedra's default library here (needs v0.5.2 or later)
res_default_library = []
for n in 2:6
    @time f1476(n)
    push!(res_default_library, f1476(n))
end

  0.000865 seconds (5.16 k allocations: 281.656 KiB)
  0.012163 seconds (33.94 k allocations: 2.665 MiB)
  0.054300 seconds (114.22 k allocations: 11.287 MiB, 12.06% gc time)
  0.532285 seconds (421.96 k allocations: 73.884 MiB, 4.60% gc time)
  8.534117 seconds (1.68 M allocations: 832.042 MiB, 2.19% gc time)
```
Hence runtime roughly increases by a factor of 10 if you increase the dimension by one... so be prepared for ~15 minutes for dimension eight 😄  The bottleneck seems to be the conversion to the vertex representation.

---

I'd be happy to follow up the discussion and code writing/reviewing with any of the ideas in this thread to improve this:

- Implement iterative refinement in high-dimensions (this is #969)
- Implement a generalization of a custom number of directions in n-dimensions, either random (this is #729), see the ideas [in this](http://extremelearning.com.au/how-to-generate-uniformly-random-points-on-n-spheres-and-n-balls/), or otherwise to generalize the parameterization in `LazySets.Approximations.SphericalDirections` 
- Implement an M-sum algorithm in H-rep (this is #1496, cf. @schillic's links in [the comment above](https://github.com/JuliaReach/LazySets.jl/issues/1476#issuecomment-505413736))

**Comment by mforets** [comment]
> Implement a generalization of a custom number of directions in n-dimensions

https://github.com/JuliaReach/LazySets.jl/pull/1503 has been merged in `master` and can be applied by writing a function similar to [this one](https://github.com/JuliaReach/LazySets.jl/blob/master/src/Approximations/overapproximate.jl#L305) but instead of `AbstractDirections` using the random `Vector{Vector{N}}`. Seems to work pretty well: in the example `f1476` it can sample 1000 random directions in ~3.2secs (the time includes removing redundant constraints, otherwise it takes 0.13sec). Full code is available in [this notebook](https://nbviewer.jupyter.org/github/mforets/escritoire/blob/master/sets/HigherDimRefinement.ipynb). The drawback of this simple approach is that it is "blind" in the sense that it doesn't refine in directions that can actually improve the approximation (that is the purpose of #969).

> Implement an M-sum algorithm in H-rep

I wrote a proof of principle using LazySets + Polyhedra (with CDDLib) (cf. [this PR](https://github.com/JuliaReach/LazySets.jl/pull/1508)). It works, but the runtime depends quite heavily on the particular polytope instance and the available projection algorithms (Fourier-Moztkin or Block elimination).

Hope that helps!

**Comment by mforets** [comment]
> Implement an M-sum algorithm in H-rep (this is #1496, cf. @schillic's links in the comment above)

This feature is now available in `master` and will be added in the next release (https://github.com/JuliaReach/LazySets.jl/wiki/Release-log-tracker), see [minkowski_sum(::AbstractPolyhedron, ::AbstractPolyhedron)](https://github.com/JuliaReach/LazySets.jl/blob/master/src/concrete_minkowski_sum.jl#L65) for details or ask back if you have questions!
