### ISSUE TITLE
Make box_approximation an alias

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1556]
We have some methods like `overapproximate(Z::Zonotope, ::Type{<:Hyperrectangle})`, but at the same time we have methods like `box_approximation(S::LazySet{N}))`. There should not exist two parallel ways to compute the box approximation because now `box_approximation(Z::Zonotope)` uses the fallback method. Rather, one of the two ways should be an alias for the other, as in:
```julia
box_approximation(X) = overapproximate(X, Type{Hyperrectangle})
```

**Comment by mforets** [comment]
I agree to let `box_approximation` be just an alias for an overapproximation with a Hyperrectangle through the `overapproximate` interface. There are some other special cases, though, such as approximation with a `BallInf`, and other particular dispatch cases for `box_approximation`. I saw that you are considering this in #1716. At a later stage we should also review the functions in the Parallel module, since they also use the `box_approximation` names.
