### ISSUE TITLE
Minkowski difference with singleton

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1587]
```julia
minkowski_difference(X::LazySet, S::AbstractSingleton) = translate(X, -element(S))
minkowski_difference(X::LazySet, ::ZeroSet) = X

MinkowskiDifference(X::LazySet, S::AbstractSingleton) = Translation(X, -element(S))
@neutral(MinkowskiDifference, ZeroSet)
```

**Comment by ueliwechsler** [comment]
Just to clarify, because I got confused in the beginning when I looked at the equations.

In this case, the `minkowsk_difference` of a lazy set with a singleton  `A - B = {a | a + B ⊆ A }`, i.e. the Ponytragin Difference correspond to the "real" Minkowski Difference `A - B = {a-b | a∈ A, b∈B} = A + reflect(B)`.  Right?

**Comment by schillic** [comment]
It says `X - S` where `S = {x}` is `X - S = X - {x} = X + {-x}` in the first line and `X - {0} = X` in the second line.

**Comment by mforets** [comment]
> In this case, the minkowsk_difference of a lazy set with a singleton A - B = {a | a + B ⊆ A }, i.e. the Ponytragin Difference correspond to the "real" Minkowski Difference A - B = {a-b | a∈ A, b∈B} = A + reflect(B). Right?

Yes, i think that in this particular case the 2 notions are the same.
