### ISSUE TITLE
HPolygon and HPolytope

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#191]
It would be convenient to have a `HPolytope` constructor from a `HPolygon` (and conversely). Also, note that the their fields are `constraints_list` and `constraints` respectively; we should decide for one of these names..

**Comment by schillic** [comment]
Is the motivation to 1. use the external library also for `HPolygon`s or 2. for the user to switch between them?
We could even introduce a `Polytope` function that creates an `HPolygon` instance for 2D sets and an `HPolytope` instance otherwise.

👍 for unifying the name; I would go for `constraints`.
