### ISSUE TITLE
_isapprox method for Array{<:LazySet}

### ISSUE THREAD

**Issue by ueliwechsler** [JuliaReach/LazySets.jl#1916]
Is was trying to check if two HPolyhedron are equivalent by calling
```julia
isequivalent(HPolyhedron(rand(2,2), rand(2)), HPolyhedron(rand(2,2), rand(2)))
ERROR: MethodError: no method matching _isapprox(::Array{HalfSpace{Float64,VN} where VN<:AbstractArray{Float64,1},1}, ::Array{HalfSpace{Float64,VN} where VN<:AbstractArray{Float64,1},1})
Stacktrace:
 [1] isapprox(::HPolyhedron{Float64}, ::HPolyhedron{Float64}) at C:\Users\wueli\.julia\dev\LazySets\src\Interfaces\LazySet.jl:475
 [2] isequivalent(::HPolyhedron{Float64}, ::HPolyhedron{Float64}) at C:\Users\wueli\.julia\dev\LazySets\src\Interfaces\LazySet.jl:785
 [3] top-level scope at none:0
```

which reduceds to the following method which is not defined for `HalfSpaces`or `Array` of `HalfSpaces`
```julia 
LazySets._isapprox(HalfSpace(rand(2), rand()),HalfSpace(rand(2), rand()))  
ERROR: MethodError: no method matching _isapprox(::HalfSpace{Float64,Array{Float64,1}}, ::HalfSpace{Float64,Array{Float64,1}})
```
I am not sure if I did something wrong or if this feature is missing.

**Comment by schillic** [comment]
Indeed we do not have `_isapprox` for two `Vector`s of `LazySet`s, which prevents you from comparing many polyhedron types. I am quite surprised that this never came up before.

However, the implementation is nontrivial because you do not want to care about the order of the constraints. Assuming that the semantics for *any* `Vector`s of `LazySet`s is to abstract from the order (which I rather doubt), a first implementation could use `ispermutation`, which uses approximate comparison:

```julia
function _isapprox(x::AbstractVector{S}, y::AbstractVector{S};
                   kwargs...) where {S<:LazySet}
    return ispermutation(x, y)
end
```
However, `ispermutation` does not let you specify the tolerance options of `_isapprox`. From the point of `isequivalent` this is fine (because you cannot specify these options there either). But when calling `_isapprox` manually for two `HPolyhedron` instances with these options specified, the behavior would be unexpected. The proper integration would be to make all the involved functions (`ispermutation` and `_in` as far as I can see) accept the tolerance options and pass them on.

But as I said above, I am not sure that we should *always* ignore the order of elements when comparing two `Vector`s. So I guess we rather need individual implementations of `_isapprox` for the respective set types.

**Comment by ueliwechsler** [comment]
I  see, thanks for the explanation. This method you propose fixes the problems I have encountered 😃 

So, would it be appropriate to make a PR with this proposed method or would you rather wait for
an implementation that allows to specify the tolerances?

**Comment by schillic** [comment]
I think I lead you to the wrong path with my suggesion in the middle of my post. The much more important part is the last paragraph where I basically say that we should not use this fix as there may be set types where the order of elements in `Vector`s matters.

#### Proposal 1

I would define methods for `≈` for those set types that do not work.

https://github.com/JuliaReach/LazySets.jl/blob/9c0853f96d8602a70879922561b4a865d1430543/src/Interfaces/LazySet.jl#L468-L481

What all of these implementations would do is call a new function `_isapprox_unordered(x, y)` for two vectors.

Here is the example for `HPolytope`:

```julia
function ≈(X::HPolytope, Y::HPolytope) 
    return _isapprox_unordered(X.constraints, Y.constraints)
end
```

This function `≈` is called in `isequivalent, so it will fix your original problem.

https://github.com/JuliaReach/LazySets.jl/blob/9c0853f96d8602a70879922561b4a865d1430543/src/Interfaces/LazySet.jl#L784-L789

#### Proposal 2

Here is an alternative idea that allows to stick with just a single default implementation of `≈`. We could define a method `unordered_vector_comparison(::Type{<:LazySet}) = false` that you can redefine to `true` for set types where you want to allow comparison of *all* `Vector`s in an unordered way. Typically this should be sufficient (I have not checked, though). Then if you modify the above default implementation of `≈` such that it handles `Vector`s with the `ispermutation` implementation, I think we are good.
The point here is that each `LazySet` type needs to explicitly opt in by overriding `unordered_vector_comparison`. This way we make sure that nothing unexpected happens.

**Comment by mforets** [comment]
I stumbled upon this same problem today,

```julia
julia> using Revise, LazySets
[ Info: Recompiling stale cache file /home/mforets/.julia/compiled/v1.2/LazySets/NjrGc.ji for LazySets [b4f0291d-fe17-52bc-9479-3d1a343d9043]

julia> using Polyhedra

julia> v = rand(VPolytope);

julia> isequivalent(v, v)
ERROR: MethodError: no method matching _isapprox(::Array{Array{Float64,1},1}, ::Array{Array{Float64,1},1})
Stacktrace:
 [1] isapprox(::VPolytope{Float64}, ::VPolytope{Float64}) at /home/mforets/.julia/dev/LazySets/src/Interfaces/LazySet.jl:475
 [2] isequivalent(::VPolytope{Float64}, ::VPolytope{Float64}) at /home/mforets/.julia/dev/LazySets/src/Interfaces/LazySet.jl:785
 [3] top-level scope at REPL[4]:1
```
The approximate equality check fails,

```julia
julia> v ≈ v
ERROR: MethodError: no method matching _isapprox(::Array{Array{Float64,1},1}, ::Array{Array{Float64,1},1})
Stacktrace:
 [1] isapprox(::VPolytope{Float64}, ::VPolytope{Float64}) at /home/mforets/.julia/dev/LazySets/src/Interfaces/LazySet.jl:475
 [2] top-level scope at REPL[6]:1
```
About the solution strategy, i like proposal 1.
