### ISSUE TITLE
Improve performance of  minkowski_sum of two Zonotopes

### ISSUE THREAD

**Issue by ueliwechsler** [JuliaReach/LazySets.jl#1975]
As discussed on gitter, the performance of the `minkowsk_sum` for two `Zonotope` can be improved.

As far as I understand it, this can be done in two ways.
1. set `remove_zero_generators` to `false`
```julia
function minkowski_sum_v2(Z1::Zonotope{N}, Z2::Zonotope{N}) where {N}
    G = hcat(Z1.generators, Z2.generators)
    return Zonotope(Z1.center + Z2.center, G, remove_zero_generators=false)
end
```
2. improving the performance of the `delete_zero_columns!` method
https://github.com/JuliaReach/LazySets.jl/blob/054f1d2aac78e074595855b25fd35c3b789c7ff2/src/Sets/Zonotope.jl#L96

Here some benchmark, just for fun ;)
```julia
using LazySets
using BenchmarkTools

function minkowski_sum_v2(Z1::Zonotope{N}, Z2::Zonotope{N}) where {N}
    G = hcat(Z1.generators, Z2.generators)
    return Zonotope(Z1.center + Z2.center, G, remove_zero_generators=false)
end

n = 100
P = convert(Zonotope, BallInf(zeros(n), 1.0))
Q = convert(Zonotope, BallInf(zeros(n), 2.0))
@btime minkowski_sum($P, $Q)
@btime minkowski_sum_v2($P, $Q)

## n = 10
# 2.511 μs (94 allocations: 8.41 KiB)
#881.836 ns (33 allocations: 3.80 KiB)
## n = 20
# 4.671 μs (154 allocations: 14.61 KiB)
# 916.667 ns (33 allocations: 5.47 KiB)
## n = 100
# 35.600 μs (634 allocations: 64.47 KiB)
# 1.867 μs (33 allocations: 19.06 KiB)
```

**Comment by schillic** [comment]
Option 1 has been implemented in #1962.

**Comment by ueliwechsler** [comment]
Ah cool, that's great. My bad.

**Comment by mforets** [comment]
Thanks for the benchmarks @ueliwechsler, some comments:

- In the release [v1.28.0](https://github.com/JuliaReach/LazySets.jl/releases/tag/v1.28.0) we added the option `remove_zero_generators` but set to `true` by default: this is the same default of the Zonotope constructor, so the performance does not really change :) unless you compute `minkowski_sum(Z1, Z2, remove_zero_generators=false)`.
- Arguably the default value should be of `remove_zero_generators_` should be turned to `true`, but there are different positions on this design choice.
- I think that the function `remove_zero_generators` is linear in the matrix size, because it has to check for zeros, column by column. If the matrix was stored eg. in a sparse format this check could be made faster. Currently we don't have an implementation for sparse matrices. Also, the current implementation copies over the non-zero part of matrix `A`, so if the matrix `A` does not have zeros, it still makes a copy. Perhaps the algorithm can be considered again.

**Comment by mforets** [comment]
> Also, the algorithm can be considered again, if we can improve it.

An easy improvement is to use a view in the loop over columns:

```julia
function dzc!(A::AbstractMatrix)
    n = size(A, 2)
    nonzero_columns = Vector{Int}()
    sizehint!(nonzero_columns, n)
    @inbounds for i in 1:n
        if !iszero(view(A, :, i))
            push!(nonzero_columns, i)
        end
    end
    if length(nonzero_columns) == n
        return A
    else
        return view(A, :, nonzero_columns)
    end
end
```

```julia
julia> A = rand(100, 100);

julia> @btime LazySets.Arrays.dzc!($A);
  545.428 ns (2 allocations: 896 bytes)

julia> @btime delete_zero_columns!($A);
  8.320 μs (102 allocations: 88.38 KiB)
```
