### ISSUE TITLE
Remove zero generators of projected Zonotope

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#2147]
Since #2072 the projection of a zonotope creates sets of the wrong dimension.

```julia
julia> using LazySets, LinearAlgebra, SparseArrays, Plots

julia> Z = Zonotope(ones(49), Diagonal(ones(49)));

julia> M = sparse([1, 2], [1, 26], [1.0, 1.0], 2, 49);

julia> Z2 = linear_map(M, Z)
Zonotope{Float64,Array{Float64,1},SparseMatrixCSC{Float64,Int64}}([1.0, 1.0], 
  [1,  1]  =  1.0
  [2, 26]  =  1.0)

julia> M * Z.generators
2×49 SparseMatrixCSC{Float64,Int64} with 2 stored entries:
  [1,  1]  =  1.0
  [2, 26]  =  1.0

julia> size(Z2.generators)
(2, 49)

julia> remove_zero_generators(Z2)
Zonotope{Float64,Array{Float64,1},SparseMatrixCSC{Float64,Int64}}([1.0, 1.0], 
  [1, 1]  =  1.0
  [2, 2]  =  1.0)
```

I suggest that we check the dimension of the map and if it is not a square matrix we remove zero generators.

**Comment by mforets** [comment]
> zonotope creates sets of the wrong dimension.

I don't see where a problem with dimensions in this example; if you ask for `dim(Z2)` it should give 2. Removing zero generators for non-square matrices (projections or lifts) is another thing. I agree that we may want to consider this by default.

After a though, since we have a concrete projection `project`, i propose to remove generators *in that function* instead main`linear_map`. There can be an option of course as this adds an instability because unless you are using static matrices, the size is not known at compile time. The option also makes sense for square matrices. OTOH, projections, in most use cases you will be adding zero generators because one usually projects on 2 variables..)

**Comment by schillic** [comment]
> I don't see where a problem with dimensions in this example; if you ask for dim(Z2) it should give 2.

True, but if you try to plot `Z`, it will run out of memory because it tries to create the vertices of this 49-dimensional generator matrix.

**Comment by schillic** [comment]
> After a thought, since we have a concrete projection project (or projection), i propose to remove generators in that function instead mainlinear_map.

The problem is that you are not forced to use `project` for a projection. The check for the matrix dimension is super cheap. I think we can do that in `linear_map` as well.

**Comment by mforets** [comment]
> True, but if you try to plot Z, it will run out of memory because it tries to create the vertices of this 49-dimensional generator matrix.

Ok. Shouldn't `vertices_list` remove zero generators beforehand? Since computing the vertices is anyways expensive, one can just make this intermediate simplification. (actually, it would be more interesting to remove zero generators to the used tolerance `ztol`)

I'm a bit reluctant to make intermediate simplifications in "basic" operations such as the `linear_map` for a zonotope. Also, matrices which generate zero columns are very particular (a set of measure zero in the space of matrices) so i would say that if one wants to do a projection just use `project`, instead of creating the projection matrix manually.

**Comment by schillic** [comment]
So to summarize: remove zero generators in `project` and in `vertices_list`?
