### ISSUE TITLE
Use promotion for support function of an intersection of half-spaces

### ISSUE THREAD

**Issue by dpsanders** [JuliaReach/LazySets.jl#2348]
```jl
H1 = HalfSpace([1.0, 1.0], 1.0)
H2 = HalfSpace([-1.0, -1.0], 1.0)

ρ([1, 0], H1 ∩ H2)
```
gives
```jl
MethodError: no method matching ρ(::Array{Int64,1}, ::Intersection{Float64,HalfSpace{Float64,Array{Float64,1}},HalfSpace{Float64,Array{Float64,1}}})
```

**Comment by dpsanders** [comment]
I can't actually find anything in the docs about how to use ρ.

**Comment by dpsanders** [comment]
Ah this was a problem with the types (the array was integers, the half-space was floats).
Maybe they should be auto-converted?

**Comment by mforets** [comment]
> Maybe they should be auto-converted?

Yes.. It's a common issue but since the conception of the library we require that the sets (and directions as in this case) have the same numeric types. That of course shall be generalized using Julia's default promotion mechanism for ease of use, but we haven't implemented it yet.

It's related to https://github.com/JuliaReach/LazySets.jl/issues/1182 and https://github.com/JuliaReach/LazySets.jl/issues/2334 .. so we may close this issue as a duplicate.

**Comment by mforets** [comment]
This is now fixed:

```julia
julia> using LazySets

julia> H1 = HalfSpace([1.0, 1.0], 1.0)   # set with floats
HalfSpace{Float64,Array{Float64,1}}([1.0, 1.0], 1.0)

julia> H2 = HalfSpace([-1.0, -1.0], 1.0) # set with floats
HalfSpace{Float64,Array{Float64,1}}([-1.0, -1.0], 1.0)

julia> ρ([1, 0], H1 ∩ H2)  # direction with ints
Inf

julia> ρ([1, 1], H1 ∩ H2) # direction with ints
1.0
```
