### ISSUE TITLE
Counterexample for containment check in zonotope

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#246]
Let:

```julia
c = [0, 0.]
G =  [0.75  -0.05  1.0  1.0   0.25  0.05   0.0;
      0.5    0.95  2.5  1.0  -0.5   0.05  -1.5]
Z = Zonotope(c, G)
```

the result of `[3., 3] ∈ Z` is false but should be `true`.

**Comment by schillic** [comment]
Good finding. The implementation is clearly unsound. It finds *one* solution of the linear equation and then checks if this solution satisfies the domain constraint (-1 ≤ s ≤ 1). However, if this is not satisfied, the answer does not have to be `false` because we might just have selected the wrong solution. Thus we must solve an LP that enforces the domain constraint.

**Comment by schillic** [comment]
[Here](https://graphics.stanford.edu/~anguyen/papers/zonotope.pdf) is a more efficient implementation (Section 5.1).

**Comment by mforets** [comment]
We could eventually implement that algorithm and others in that paper, most of which are for the important cases 2d and 3d. PR #247 implements the standard way using an LP.
