### ISSUE TITLE
AssertionError in Iterative refinement

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#260]
`AssertionError: R.refinable`

In lines 71-73 we do:
```julia
approx_error = min(norm(q - σ(ndir, S)), dot(ndir, q - p1))
refinable = (approx_error > TOL(N)) && !(norm(p1-q, 2) < TOL(N) || norm(q-p2, 2) < TOL(N))
ap = LocalApproximation{N}(p1, d1, p2, d2, q, refinable, approx_error)
```
In line 185 we check:
```julia
if Ω.approx_list[i].err <= ɛ
```
Now it can happen that `refinable == false`, although `Ω.approx_list[i].err`, which is `approx_error` above, is `<= ɛ`.
Instead, we should check:
```julia
approx = Ω.approx_list[i]
if !approx.refinable || approx.err <= ɛ
```

@mforets: Do you agree?

**Comment by mforets** [comment]
is in `refine` where this assertion error is triggered? do you have an example raising this error that we can inspect?

**Comment by schillic** [comment]
Yes, the only assertion there, `@assert R.refinable`.
The example is motor with a new wrapping-effect version of `Reachability`. I will push the branch now.

**Comment by mforets** [comment]
my guess is that this case is pathological (`NaN`'s on the place), but maybe i'm wrong. anyways, it is completely ok to add an `or` with `!approx.refinable`, if that helps to rule out some edge case. 

basically `refinable` want's to be true whenever `approx_error` is not zero. the other pieces of the clause are there to handle degenerate cases.

**Comment by schillic** [comment]
Yes, the numbers get ridiculously big, maybe there are `NaN`s.

**Comment by mforets** [comment]
it may be due to a big overapproximation of the initial set, and that it gets fixed choosing a delta a bit smaller.

if `approx_error` is `NaN`, then `Ω.approx_list[i].err <= ɛ` will be `false` thus going to the `else` branch, even if it doesn't make sense to take the refinement. in that case, at least `refinable` is (correctly) set to `false` (since the first check `approx_error > TOL(N)` is `false`).

in sum i would go, too, for adding the extra condition `!approx.refinable || ...`.
