### ISSUE TITLE
Allow creating unbounded SymmetricIntervalHull

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#2757]
Currently the constructor of the SIH requires the set to be bounded. However, there are cases in which we are interested to query the support function of the SIH of an unbounded set. (This came up on a dense time discretization in reachability.)

**Comment by schillic** [comment]
Then we would need a new type because `SymmetricIntervalHull <: AbstractHyperrectangle`.

**Comment by mforets** [comment]
In this case I would just add a flag and set it to true by default. The proposal is on the same ground of the `check_bounds::Bool=true`  flag in the Hyperrectangle constructor: the library assumes that the radius is nonnegative, but it doesn't prevent from constructing the set if you know what you're doing.

**Comment by schillic** [comment]
Then I would remove the interface, so let `SymmetricIntervalHull <: AbstractPolyhedron` instead.

**Comment by mforets** [comment]
Avoiding the check could be (not in my case, but it is certainly possible) motivated by getting faster runtimes, since `isbounded ` may have non-zero cost (compare with `check_boundedness` in HPolytope). I don't think we need to justify adding new constructor flags with far reaching changes in the library.

**Comment by schillic** [comment]
> The proposal is on the same ground of the `check_bounds::Bool=true` flag in the Hyperrectangle constructor: the library assumes that the radius is nonnegative, but it doesn't prevent from constructing the set if you know what you're doing.

This is something else because it only reasonably applies when passing a flat set whose bounds are contradictory for numerical reasons. What you propose here is a whole new behavior.

This change opens up the door to all kinds of errors that may be hard to detect. With `SymmetricIntervalHull <: AbstractHyperrectangle` the library can choose methods that are just wrong when applied to unbounded sets. One example is that `isbounded(::SymmetricIntervalHull)` returns `true`, but there may be more subtle issues like `vertices_list` giving you `Inf` entries etc. Even if you can live with all current problems, we may add other functionality to `AbstractHyperrectangle` later that adds more problems and you always need to keep this in mind. I do not see the benefit of adding something for which you do not know whether the result is correct or not.

If this feature is needed, we should add a new type. This costs 10 minutes now. I do not want to spend hours in debugging reports later.

**Comment by mforets** [comment]
Hmm i see this as a feature to selectively remove an assertion (we have remove_assertions anyways, but that acts globally and it is more cumbersome to quickly change a flag in the constructor). I would discourage using this flag in general and I don't plan to set it to `true` in RA, so I don't see there's a motivation for a new type. Compare with the `check_boundedness` flag in HPolytope (maybe we should turn it to `true` , btw).

**Comment by schillic** [comment]
I added a proposal in #2759.

**Comment by schillic** [comment]
> i see this as a feature to selectively remove an assertion

I know, but this assertion is there for a reason because some behavior relies on it.

**Comment by mforets** [comment]
the underlying proposal is: if we know what we are doing, let the user define how to use the types. i'm definitely in favor of that, the motivations may vary. here are some existing examples:

- `check_bounds` in Hyperrectangle (to elide the radius check)
- `check_boundedness` in HPolytope (to elide the boundedness check)
- `apply_convex_hull` in VPolygon (to elide computing the convex hull) 

there may be more.

we should stress in the docstrings what the flags actually mean and that other functions of the library rely on those mathematical assumptions, use at your own risk, etc. i don't think that we need to specify which function requires which assumption, that is too much level of detail.

**Comment by schillic** [comment]
> here are some existing examples

As I said before, these existing checks have the purpose to avoid a check that is still supposed to return `true`, just to save time. I do not see these flags for creation of invalid objects. We already had several bug reports where unbounded `HPolytope`s were constructed and that just costs time to debug and answer. Here you explicitly want to create an invalid object.

> they know what they're doing

The problem is that it is hard to know because you get functionality automatically.

> we should stress in the docstrings what the flags actually mean

Yes, this is the least requirement I have.

> i don't think that we need to specify which function requires which assumption

I totally agree.
