### ISSUE TITLE
Symbolic symmetric interval hull

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#3]
The symmetric interval hull is computed explicitly in [Approximations.box_approximation_helper](https://github.com/mforets/LazySets.jl/blob/master/src/Approximations.jl#L226), through 2n support function evaluations.

An application of a new lazy (total or partial) type, symmetric interval hull, is to speedup the discretization phase; the explicit form can take up to 97% of the time for n>10000.

**Comment by schillic** [comment]
We discussed a possible implementation that assumes *normal directions* to save half of the support vector computations.

**Comment by schillic** [comment]
Would it be helpful to have the type remember the results it already computed? In this case, it could remember the borders (i.e., half-spaces). I do not have any intuition how often we need to know the support vector of the same direction twice.

I also do not know if it is reasonable to infer more information from partial knowledge. For instance, if you have the right border in one dimension, since we know that the center is in the origin, we also know the left border. The problem is that we do not know which border we found. At least we know for sure that for directions with the same absolute values we get support vectors with the same absolute values, but again I do not know if this use case ever occurs.

**Comment by schillic** [comment]
To get the support vector in a non-unit direction, it suffices to compute the symmetric interval hull in the direction's nonzero dimensions.
