### ISSUE TITLE
Support vector of Polygon

### ISSUE THREAD

**Issue by gzagatti** [JuliaReach/LazySets.jl#3324]
I wanted to plot two polygons one after the other.

While the following works:

```julia
A = rand(2,2)
P1 = Polygon([[0., 0.], [0., 1.], [1., 1.], [1., 0.]])
P2 = Polygon([A*[0., 0.], A*[0., 1.], A*[1., 1.], A*[1., 0.]])

plot([P1, P2], ratio=1)
```

The following raises an error:

```julia
plot(P1, ratio=1)
plot!(P2, ratio=1)
```

```julia
ERROR: MethodError: no method matching σ(::ReachabilityBase.Arrays.Sing
leEntryVector{Float64}, ::Polygon{Float64, Vector{Float64}})

Closest candidates are:
  σ(::ReachabilityBase.Arrays.SingleEntryVector, ::BallInf)
   @ LazySets ~/.julia/packages/LazySets/yRTCH/src/Sets/BallInf.jl:181
  σ(::ReachabilityBase.Arrays.SingleEntryVector, ::Hyperrectangle)
   @ LazySets ~/.julia/packages/LazySets/yRTCH/src/Sets/Hyperrectangle.
jl:270
  σ(::ReachabilityBase.Arrays.SingleEntryVector, ::CartesianProduct)
   @ LazySets ~/.julia/packages/LazySets/yRTCH/src/LazyOperations/Carte
sianProduct.jl:165
  ...
```

Am I missing something?

I'm using Julia version 1.9.0, LazySets v2.7.6 and Plots v1.38.11.

**Comment by schillic** [comment]
The problem is that `σ` is not implemented. `plot!` calls an internal helper function that computes the box approximation in order to update the plot limits. The appropriate method of `σ` would be easy to add (can use the same implementation as `VPolytope`). I can fix this it at some later point.

Since your polygon is convex, as a workaround, you can use `VPolygon` for convex polygons in vertex representation.
The `Polygon` is used for non-convex polygons and is generally not well supported.

**Comment by gzagatti** [comment]
Thanks for the detailed and quick response. 

I'll use `VPolygon` which I was not aware and is enough for my purposes. I am only illustrating some simple operations.

I will leave the issue open if you plan to solve at later date.
