### ISSUE TITLE
Caching the JuMP model in linprog

### ISSUE THREAD

**Issue by Zinoex** [JuliaReach/LazySets.jl#3336]
For the workload I am dealing with currently, the overhead in instantiating a JuMP model in `linprog` is substantial (small polyhedra, many evaluations of `isdisjoint` and `σ`). The main issue here is that when a JuMP model is instantiated, it [adds all bridges to the model](https://github.com/jump-dev/MathOptInterface.jl/blob/master/src/Bridges/Bridges.jl#L56), which is [known to have a lot of overhead](https://jump.dev/JuMP.jl/stable/tutorials/getting_started/performance_tips/#Disable-bridges-if-none-are-being-used). A possible fix to this is to cache the JuMP model and call `empty!` on the model. According to [a comment in the JuMP source](https://github.com/jump-dev/JuMP.jl/blob/c5935e692f5835f1358fba6e85d391bb34fd5f82/src/JuMP.jl#L676), this will not clear the bridge types and thus reduce the latency. I have also been through the call stack manually, and `empty!` on the model calls `empty!` on LazyBridgeOptimizer (AbstractBridgeOptimizer method), which does not clear the bridge types or the Bellman-Ford graph on the object. Hence, if the JuMP model is cached, significant overhead in MOI is reduced.

**Comment by schillic** [comment]
Having a better solver API would be great, but we do not have time for that at the moment. However, I think there is a relatively simple implementation you can use. Since the solver is created in only two methods, you can just override them with your own implementation, in which you would then call `empty!` on your predefined solver and return it. The relevant methods are below (assuming you work with floating-point numbers; otherwise search in these files for the `Rational` methods):

#### `linprog`

https://github.com/JuliaReach/LazySets.jl/blob/494db08ea0a1dde0ca93dbd27f3329290e77f085/src/Utils/lp_solvers.jl#L2-L4

#### `Polyhedra.jl`

https://github.com/JuliaReach/LazySets.jl/blob/494db08ea0a1dde0ca93dbd27f3329290e77f085/src/Initialization/init_Polyhedra.jl#L16-L24

**Comment by mforets** [comment]
Do you have an idea how to implement such feature in LazySets? 

Since `σ_helper(d::AbstractVector, P::HPoly, solver)`, which calls `linprog` under the hood, a potential approach is to enable passing a solver cache via `σ(d::AbstractVector{M}, P::HPoly{N}; solver=default_lp_solver(M, N), cache=...) where {M, N}`.

**Comment by mforets** [comment]
@schillic Ah, you would dispatch on a custom `solver` in `lp = linprog(c, A, sense, b, l, u, solver)` which also holds the cache. I agree, that seems like a first step towards a less hacky solution.

**Comment by schillic** [comment]
No, I suggest to redefine `default_lp_solver` such that it does not always create a new solver but reuse the same one.

**Comment by Zinoex** [comment]
The solution that @schillic proposes will not solve the problem. `default_lp_solver` does not actually return a solver, instead it returns a solver factory (in this case, wrapped in an OptimizerWithAttributes, which uses the underlying factory followed by setting the attributes specified). Then in `linprog` when a model is constructed with `Model(solver)`, the solver is instantiated from the factory and the bridges are added to the model (not the solver). So modifying `default_lp_solver` to reuse the solver factory does not actually reuse the bridges, model, or solver.

I think a solution would be something along the lines of @mforets' suggestion.

**Comment by schillic** [comment]
Hm okay, I do not know what `Model(solver)` does under the hood.

Since this is the only thing that happens with the solver, a potential change could be to let `linprog` either receive `solver` (the current interface) or the model directly. But this would only change the internal interface. To give the user the option, all user API functions would have to accept a solver OR a model.

I am not sure how the interface should look like to support automatic resetting of the model and at the same time accept a user-passed model that _should not_ be reset. How can this be detected?

Anyway, I guess for your purposes you can just override `linprog` and replace `model = Model(solver)` accordingly.

**Comment by Zinoex** [comment]
> I am not sure how the interface should look like to support automatic resetting of the model and at the same time accept a user-passed model that _should not_ be reset. How can this be detected?

If a solver is passed, we can just construct a model. If a model is passed, we can empty the model after optimization (and possibly before too, as we don't know if a user has added anything to the model). Letting the parameter be `solver_or_model`, we can use multiple dispatch in `linprog` to figure out which of the two cases. I am not sure we will ever have a case where we do not want to reset a user-passed model. 

I also want to clarify some terminology regarding JuMP. Emptying the model means delete variables, constraints, and objectives, whereas resetting, in addition to the above, also deletes the bridges and the Bellman-Ford graph. So in our case, we are clearly interested in emptying over resetting.

**Comment by schillic** [comment]
I would not empty the model after the calculation (a user could want to post-process it).

The rest sounds good to me. To benefit from the performance gain in the general library, we could construct a cached (global) default model internally and change calls to `default_lp_solver` by `default_lp_solver_model` everywhere.

I think we have a plan. Are you interested in adding this functionality? Otherwise I can do that (but would take 1-2 weeks before I get there), but I would need to know how to _empty_ (thanks for the clarification) a model then.
