### ISSUE TITLE
Add HPolygon constructor from simple representation (A, b)

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#474]

**Comment by schillic** [comment]
We already have this for `HPolytope`, so it would be copy-paste. Maybe we should have a meta-function in `AbstractPolytope` that takes as argument the set type and creates the respective constructor.

**Comment by schillic** [comment]
The constraints should probably be sorted automatically, with an option to skip the sorting.

**Comment by schillic** [comment]
I suggest to introduce conversion functions from `AbstractVector{LinearConstraint{N}}` to `(A, b)` and back from `(A, b)` to `Vector{LinearConstraint{N}}`. This simplifies the code. How should we call them? `matvec` and `rows`? `matrix` and `constraints`? ([maybe related](https://en.wikipedia.org/wiki/Linear_programming#Standard_form))...

**Comment by mforets** [comment]
> The constraints should probably be sorted automatically, with an option to skip the sorting.

👍 

>  I suggest to introduce conversion functions ...

👍 . these will be internal functions. one way is to call them could be called `tosimplehrep(v::AbstractVector{LinearConstraint{N}})` and `tolinearconstraints(A::Matrix, b::Vector)`

**Comment by mforets** [comment]
because for conversion of things we would typically overload `convert`, but these could be considered special / internal conversions..

**Comment by schillic** [comment]
Okay for the names, and I agree that we better do not use `convert` (because I am not sure whether two inputs (matrix/vector) work).
The functions could also be useful for a user or for playing around in the REPL, but I am okay with not exporting them.
Note that we should allow abstract matrices/vectors: `tolinearconstraints(A::AbstractMatrix, b::AbstractVector)`
