### ISSUE TITLE
"Safely" querying support vectors 

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#478]
Proposal: check that in support vector queries the numeric type of the given direction matches that of the lazy set, eg. as in `σ(d::V, B::Ball1{N}) where {N<:Real, V<:AbstractVector{N}}`.

**Comment by schillic** [comment]
I think we do not need the `V` type parameter for inputs because (1) we never use `V` and (2) the performance should be the same (at least in my experiments). It might make a difference for outputs, as we have seen in #290 and #293, but this does not matter here.
That said, I will go for `σ(d::AbstractVector{N}, B::Ball1{N}) where {N<:Real}`.

It might be possible to do
`σ(d::AbstractVector{N}, B::Ball1{N})::V where {N<:Real, AbstractVector{N}}`
but I am not sure.
