### ISSUE TITLE
Revise numeric type in iterative_refinement.jl

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#571]
For some arguments we currently do not require `N`.
In general the algorithms rely on `norm`, which exists for `Float64` and `Float32`, but not for `Rational` types, so I suggest that we restrict `N <: AbstractFloat`.

**Comment by mforets** [comment]
makes sense that algorithms in `iterative_refinement.jl` work for floats only, since it involves taking square roots and such. 

for "exact" answers, though, it would be possible to write an interval-arithmetic based algorithm. since maybe the current one just works with intervals (?)

note that `norm` works for rational although it does automatically converts the answer (even if in this case there is a meaningful rational answer): 

```julia
julia> norm([1//1, 2//1], Inf)
2.0
```

**Comment by schillic** [comment]
My basic concern is that, from the outside, the function looks like it could work with `Rational`s, but in most cases it will fail because internally it converts to `Float64` and then breaks because the output type is wrong.
