### ISSUE TITLE
Dimension error for default Polyhedra backend in >= v0.7

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#842]
With #831 we introduced a misuse in the default backend of `Polyhedra`: [Here](https://github.com/JuliaReach/LazySets.jl/pull/831/files#diff-a15e0da633542d9b2a8d9dcf13867de6R152) we should not pass `2` but `dim(P)` (and the same a few lines below). The problem is that we do not have `P` here...

**Comment by mforets** [comment]
yes, i hardcoded 2 in [default_polyhedra_backend](https://github.com/JuliaReach/LazySets.jl/pull/831/files#diff-a15e0da633542d9b2a8d9dcf13867de6R152) because the `default_library` for `d > 1` does not depend on `d`, there is just one `DefaultLibrary{_default_type(T)}()`, see [this function](https://github.com/JuliaPolyhedra/Polyhedra.jl/blob/master/src/default.jl#L45). 

presumably the default interval library is specialized for interval computations, and i would expect that the general library also works for `d=1` (but i havent' checked).

if we want we can still update our functions passing `P` as well, eg.

```julia
function convex_hull(P1::HPoly{N},
                     P2::HPoly{N};
                     backend=default_polyhedra_backend(P1, N)) where {N}
    @assert isdefined(Main, :Polyhedra) "the function `convex_hull` needs " *
                                        "the package 'Polyhedra' to be loaded"
    Pch = convexhull(polyhedron(P1, backend), polyhedron(P2, backend))
    return convert(typeof(P1), Pch)
end

...

    function default_polyhedra_backend(P, N::Type{<:AbstractFloat})
        return default_library(LazySets.dim(P), Float64)
    end
```

**Comment by schillic** [comment]
> i would expect that the general library also works for d=1 (but i havent' checked).

There are problems with 1-dimensional cases, see #843.
